In [23]:
import pandas as pd
from pathlib import Path

In [24]:
raw = pd.read_csv(Path.cwd() / 'data' / 'meta_ads_report_01.09.26-30.09.26.csv')

In [25]:
raw.head()

,Reporting starts,Reporting ends,Campaign name,Account name,Account ID,Campaign ID,Objective,Attribution setting,Amount spent (PLN),Impressions,...,Landing page views,Cost per landing page view (PLN),Content views,Adds to cart,Checkouts initiated,Adds of payment info,Purchases,Cost per purchase (PLN),Purchases conversion value,Purchase ROAS (return on ad spend)
0,2026-09-30,2026-09-30,Сайт | Продажи | 15.04.2026,Vibe sushi 1,1546686866463549,52507512578657,Sales,"7-day click, 1-day view, or 1-day engaged-view",32.87,1554,...,3.0,10.956667,12.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-09-30,2026-09-30,Бургер 50% 03/04,Vibe sushi 1,1546686866463549,6999401820253,Sales,"7-day click, 1-day view, or 1-day engaged-view",0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-09-30,2026-09-30,Котик (amour) - 01/04,Vibe sushi 1,1546686866463549,6998411340053,Sales,"7-day click, 1-day view, or 1-day engaged-view",0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-09-30,2026-09-30,Бургер 50% 21.03,Vibe sushi 1,1546686866463549,6990460801653,Sales,"7-day click, 1-day view, or 1-day engaged-view",0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-09-30,2026-09-30,Рол в подарок 17.03,Vibe sushi 1,1546686866463549,6988304006053,Sales,"7-day click, 1-day view, or 1-day engaged-view",0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
raw.dtypes

Reporting starts                              str
Reporting ends                                str
Campaign name                                 str
Account name                                  str
Account ID                                  int64
Campaign ID                                 int64
Objective                                     str
Attribution setting                           str
Amount spent (PLN)                        float64
Impressions                                 int64
Reach                                       int64
Frequency                                 float64
CPM (cost per 1,000 impressions) (PLN)    float64
Link clicks                               float64
Outbound clicks                           float64
CTR (link click-through rate)             float64
Outbound CTR (click-through rate)         float64
CPC (cost per link click) (PLN)           float64
Cost per outbound click (PLN)             float64
Landing page views                        float64
Cost per landing page view (PLN)          float64
Content views                             float64
Adds to cart                              float64
Checkouts initiated                       float64
Adds of payment info                      float64
Purchases                                 float64
Cost per purchase (PLN)                   float64
Purchases conversion value                float64
Purchase ROAS (return on ad spend)        float64
dtype: object

In [27]:
raw = raw[raw['Amount spent (PLN)'] != 0.00]

In [28]:
raw = raw.drop(['Reporting ends', 'Account name', 'Account ID', 'Campaign ID', 'Amount spent (PLN)', 'Attribution setting'], axis=1)

In [29]:
raw.columns

Index(['Reporting starts', 'Campaign name', 'Objective', 'Impressions',
       'Reach', 'Frequency', 'CPM (cost per 1,000 impressions) (PLN)',
       'Link clicks', 'Outbound clicks', 'CTR (link click-through rate)',
       'Outbound CTR (click-through rate)', 'CPC (cost per link click) (PLN)',
       'Cost per outbound click (PLN)', 'Landing page views',
       'Cost per landing page view (PLN)', 'Content views', 'Adds to cart',
       'Checkouts initiated', 'Adds of payment info', 'Purchases',
       'Cost per purchase (PLN)', 'Purchases conversion value',
       'Purchase ROAS (return on ad spend)'],
      dtype='str')

In [33]:
raw = raw.rename({
    'Reporting starts': 'date',
    'Campaign name': 'campaign_name',
    'Objective': 'objective',
    'Amount spent (PLN)': 'expenses',
    'Impressions': 'impressions', 
    'Reach': 'reach', 
    'Frequency': 'frequency',
    'CPM (cost per 1,000 impressions) (PLN)': 'CPM', 
    'Link clicks': 'link_clicks',
    'Outbound clicks': 'outbound_clicks', 
    'CTR (link click-through rate)': 'CTR',
    'Outbound CTR (click-through rate)': 'outbound_CTR', 
    'CPC (cost per link click) (PLN)': 'CPC',
    'Cost per outbound click (PLN)': 'cost_per_outbound_click', 
    'Landing page views': 'landing_page_views',
    'Cost per landing page view (PLN)': 'cost_per_landing_page_view', 
    'Content views': 'content_views', 
    'Adds to cart': 'adds_to_cart',
    'Checkouts initiated': 'checkouts_initiated', 
    'Adds of payment info': 'adds_of_payment_info', 
    'Purchases': 'purchases',
    'Cost per purchase (PLN)': 'cost_per_purchase', 
    'Purchases conversion value': 'purchases_conversion_value',
    'Purchase ROAS (return on ad spend)': 'ROAS'
    }, axis=1 
)

In [34]:
raw

,date,campaign_name,objective,impressions,reach,frequency,CPM,link_clicks,outbound_clicks,CTR,...,landing_page_views,cost_per_landing_page_view,content_views,adds_to_cart,checkouts_initiated,adds_of_payment_info,purchases,cost_per_purchase,purchases_conversion_value,ROAS
0,2026-09-30,Сайт | Продажи | 15.04.2026,Sales,1554,1083,1.434903,21.151866,11.0,11.0,0.707851,...,3.0,10.956667,12.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2026-09-30,YM | Трафик на профиль IG | CBO,Traffic,898,898,1.000000,16.815145,63.0,NaN,7.015590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2026-09-29,Сайт | Продажи | 15.04.2026,Sales,1601,1212,1.320957,18.363523,17.0,17.0,1.061836,...,12.0,2.450000,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
12,2026-09-29,YM | Трафик на профиль IG | CBO,Traffic,918,906,1.013245,16.666667,58.0,NaN,6.318083,...,1.0,15.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2026-09-28,Сайт | Продажи | 15.04.2026,Sales,2015,1345,1.498141,17.538462,9.0,9.0,0.446650,...,6.0,5.890000,12.0,2.0,3.0,3.0,1.0,35.340000,154.53,4.372666
19,2026-09-28,YM | Трафик на профиль IG | CBO,Traffic,972,966,1.006211,15.679012,63.0,NaN,6.481481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2026-09-27,Сайт | Продажи | 15.04.2026,Sales,2392,1666,1.435774,18.010033,28.0,28.0,1.170569,...,15.0,2.872000,21.0,7.0,4.0,3.0,3.0,14.360000,409.01,9.494197
26,2026-09-27,YM | Трафик на профиль IG | CBO,Traffic,1030,1008,1.021825,16.747573,81.0,NaN,7.864078,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2026-09-26,Сайт | Продажи | 15.04.2026,Sales,1746,1218,1.433498,17.588774,15.0,15.0,0.859107,...,8.0,3.838750,37.0,3.0,3.0,NaN,1.0,30.710000,196.95,6.413220
33,2026-09-26,YM | Трафик на профиль IG | CBO,Traffic,898,898,1.000000,15.456570,66.0,NaN,7.349666,...,1.0,13.880000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2026-09-25,Сайт | Продажи | 15.04.2026,Sales,1864,1311,1.421815,18.036481,13.0,13.0,0.697425,...,6.0,5.603333,96.0,26.0,6.0,4.0,5.0,6.724000,615.17,18.297739
40,2026-09-25,YM | Трафик на профиль IG | CBO,Traffic,892,866,1.030023,15.829596,51.0,NaN,5.717489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2026-09-24,Сайт | Продажи | 15.04.2026,Sales,2261,1758,1.286121,17.187085,12.0,12.0,0.530739,...,5.0,7.772000,5.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN
47,2026-09-24,YM | Трафик на профиль IG | CBO,Traffic,892,892,1.000000,15.448430,56.0,NaN,6.278027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2026-09-23,Сайт | Продажи | 15.04.2026,Sales,1570,1236,1.270227,17.401274,6.0,6.0,0.382166,...,NaN,NaN,4.0,2.0,2.0,NaN,1.0,27.320000,171.70,6.284773
54,2026-09-23,YM | Трафик на профиль IG | CBO,Traffic,987,977,1.010235,16.271530,62.0,NaN,6.281662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2026-09-22,Сайт | Продажи | 15.04.2026,Sales,2691,1934,1.391417,14.567075,17.0,17.0,0.631735,...,6.0,6.533333,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
61,2026-09-22,YM | Трафик на профиль IG | CBO,Traffic,757,757,1.000000,18.163804,62.0,NaN,8.190225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2026-09-21,Сайт | Продажи | 15.04.2026,Sales,1655,1141,1.450482,17.589124,13.0,13.0,0.785498,...,7.0,4.158571,28.0,12.0,6.0,NaN,2.0,14.555000,397.23,13.645826
68,2026-09-21,YM | Трафик на профиль IG | CBO,Traffic,857,849,1.009423,19.218203,68.0,NaN,7.934656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,2026-09-20,Сайт | Продажи | 15.04.2026,Sales,2349,1673,1.404065,19.638144,32.0,32.0,1.362282,...,20.0,2.306500,21.0,16.0,8.0,1.0,3.0,15.376667,333.65,7.232820
75,2026-09-20,YM | Трафик на профиль IG | CBO,Traffic,929,929,1.000000,18.180840,51.0,NaN,5.489774,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,2026-09-19,Сайт | Продажи | 15.04.2026,Sales,1208,992,1.217742,21.258278,20.0,20.0,1.655629,...,8.0,3.210000,27.0,4.0,2.0,1.0,1.0,25.680000,180.00,7.009346
82,2026-09-19,YM | Трафик на профиль IG | CBO,Traffic,834,803,1.038605,18.908873,61.0,NaN,7.314149,...,1.0,15.770000,32.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
84,2026-09-18,Сайт | Продажи | 15.04.2026,Sales,1806,1269,1.423168,18.881506,10.0,10.0,0.553710,...,6.0,5.683333,4.0,2.0,1.0,NaN,1.0,34.100000,252.50,7.404692
89,2026-09-18,YM | Трафик на профиль IG | CBO,Traffic,756,747,1.012048,18.862434,57.0,NaN,7.539683,...,1.0,14.260000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,2026-09-17,Сайт | Продажи | 15.04.2026,Sales,1767,1294,1.365533,19.071873,18.0,18.0,1.018676,...,9.0,3.744444,9.0,3.0,1.0,1.0,2.0,16.850000,204.53,6.069139
96,2026-09-17,YM | Трафик на профиль IG | CBO,Traffic,722,722,1.000000,17.216066,39.0,NaN,5.401662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2026-09-16,Сайт | Продажи | 15.04.2026,Sales,1825,1478,1.234777,18.827397,16.0,16.0,0.876712,...,11.0,3.123636,10.0,4.0,1.0,NaN,1.0,34.360000,109.08,3.174622
103,2026-09-16,YM | Трафик на профиль IG | CBO,Traffic,837,837,1.000000,18.793309,51.0,NaN,6.093190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,2026-09-15,Сайт | Продажи | 15.04.2026,Sales,1582,1134,1.395062,17.951960,11.0,11.0,0.695322,...,5.0,5.680000,10.0,3.0,3.0,1.0,1.0,28.400000,250.00,8.802817
110,2026-09-15,YM | Трафик на профиль IG | CBO,Traffic,807,789,1.022814,18.116481,54.0,NaN,6.691450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,2026-09-14,Сайт | Продажи | 15.04.2026,Sales,2722,1862,1.461869,14.856723,15.0,15.0,0.551065,...,8.0,5.055000,5.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN
117,2026-09-14,YM | Трафик на профиль IG | CBO,Traffic,747,736,1.014946,19.210174,42.0,NaN,5.622490,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,2026-09-13,Сайт | Продажи | 15.04.2026,Sales,3039,2021,1.503711,15.893386,20.0,20.0,0.658111,...,17.0,2.841176,10.0,9.0,6.0,4.0,4.0,12.075000,628.40,13.010352
124,2026-09-13,YM | Трафик на профиль IG | CBO,Traffic,921,912,1.009868,19.337676,61.0,NaN,6.623236,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,2026-09-12,Сайт | Продажи | 15.04.2026,Sales,1926,1292,1.490712,16.588785,14.0,14.0,0.726895,...,10.0,3.195000,7.0,5.0,5.0,3.0,3.0,10.650000,345.20,10.804382
131,2026-09-12,YM | Трафик на профиль IG | CBO,Traffic,802,802,1.000000,18.965087,47.0,NaN,5.860349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,2026-09-11,Сайт | Продажи | 15.04.2026,Sales,2131,1456,1.463599,16.391366,19.0,19.0,0.891600,...,10.0,3.493000,9.0,5.0,1.0,3.0,2.0,17.465000,369.08,10.566275
138,2026-09-11,YM | Трафик на профиль IG | CBO,Traffic,739,721,1.024965,19.566982,53.0,NaN,7.171854,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,2026-09-10,Сайт | Продажи | 15.04.2026,Sales,2314,1623,1.425755,16.356958,22.0,22.0,0.950735,...,10.0,3.785000,28.0,2.0,1.0,1.0,1.0,37.850000,108.00,2.853369
145,2026-09-10,YM | Трафик на профиль IG | CBO,Traffic,662,640,1.034375,20.377644,58.0,NaN,8.761329,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,2026-09-09,Сайт | Продажи | 15.04.2026,Sales,2141,1485,1.441751,18.776273,20.0,20.0,0.934143,...,9.0,4.466667,9.0,7.0,3.0,1.0,1.0,40.200000,108.00,2.686567
152,2026-09-09,YM | Трафик на профиль IG | CBO,Traffic,779,762,1.022310,18.087291,50.0,NaN,6.418485,...,1.0,14.090000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,2026-09-08,Сайт | Продажи | 15.04.2026,Sales,1923,1406,1.367710,14.586583,9.0,9.0,0.468019,...,3.0,9.350000,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,2026-09-08,YM | Трафик на профиль IG | CBO,Traffic,904,878,1.029613,16.526549,44.0,NaN,4.867257,...,1.0,14.940000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,2026-09-07,Сайт | Продажи | 15.04.2026,Sales,2161,1448,1.492403,14.164739,14.0,14.0,0.647848,...,5.0,6.122000,10.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN
166,2026-09-07,YM | Трафик на профиль IG | CBO,Traffic,988,966,1.022774,16.204453,79.0,NaN,7.995951,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,2026-09-06,Сайт | Продажи | 15.04.2026,Sales,3162,2112,1.497159,13.083491,19.0,19.0,0.600886,...,9.0,4.596667,22.0,18.0,4.0,2.0,4.0,10.342500,704.95,17.040126
173,2026-09-06,YM | Трафик на профиль IG | CBO,Traffic,1083,1081,1.001850,15.447830,76.0,NaN,7.017544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,2026-09-05,Сайт | Продажи | 15.04.2026,Sales,2058,1452,1.417355,13.211856,17.0,17.0,0.826045,...,9.0,3.021111,12.0,8.0,1.0,NaN,NaN,NaN,NaN,NaN
180,2026-09-05,YM | Трафик на профиль IG | CBO,Traffic,911,881,1.034052,15.356751,61.0,NaN,6.695939,...,1.0,13.990000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,2026-09-04,Сайт | Продажи | 15.04.2026,Sales,1854,1216,1.524671,16.504854,11.0,11.0,0.593312,...,6.0,5.100000,20.0,8.0,2.0,1.0,1.0,30.600000,200.00,6.535948
187,2026-09-04,YM | Трафик на профиль IG | CBO,Traffic,830,816,1.017157,16.783133,50.0,NaN,6.024096,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,2026-09-03,Сайт | Продажи | 15.04.2026,Sales,2115,1567,1.349713,14.907801,20.0,20.0,0.945626,...,9.0,3.503333,39.0,13.0,3.0,2.0,3.0,10.510000,523.20,16.593720
194,2026-09-03,YM | Трафик на профиль IG | CBO,Traffic,902,902,1.000000,17.305987,54.0,NaN,5.986696,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,2026-09-02,Сайт | Продажи | 15.04.2026,Sales,2352,1639,1.435021,14.515306,16.0,16.0,0.680272,...,4.0,8.535000,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,2026-09-02,YM | Трафик на профиль IG | CBO,Traffic,857,857,1.000000,17.584597,51.0,NaN,5.950992,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,2026-09-01,Сайт | Продажи | 15.04.2026,Sales,2766,1999,1.383692,14.396240,22.0,22.0,0.795372,...,8.0,4.977500,8.0,3.0,1.0,1.0,1.0,39.820000,154.53,3.880713
208,2026-09-01,YM | Трафик на профиль IG | CBO,Traffic,776,766,1.013055,16.675258,53.0,NaN,6.829897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN